DELETE FROM comments;
DELETE FROM bookings;
DELETE FROM requests;
DELETE FROM items;
DELETE FROM users;

ALTER TABLE users ALTER COLUMN id RESTART with 1;
ALTER TABLE items ALTER COLUMN id RESTART with 1;
ALTER TABLE requests ALTER COLUMN id RESTART with 1;
ALTER TABLE bookings ALTER COLUMN id RESTART with 1;
ALTER TABLE comments ALTER COLUMN id RESTART with 1;