DELETE FROM comments;
DELETE FROM bookings;
DELETE FROM requestItems;
DELETE FROM items;
DELETE FROM users;

ALTER TABLE users ALTER COLUMN id RESTART with 1;
ALTER TABLE items ALTER COLUMN id RESTART with 1;
ALTER TABLE requestItems ALTER COLUMN id RESTART with 1;
ALTER TABLE bookings ALTER COLUMN id RESTART with 1;
ALTER TABLE comments ALTER COLUMN id RESTART with 1;